### ISSUE TITLE
No files for install

### ISSUE THREAD

**Issue by MakeItGame** [edwardqnguyen/awbw2-electricboogaloo#2]
when running yarn it says that it does not find the install, build and dev file

**Comment by analessthanthree** [comment]
Hey,

After cloning the repository, did you make sure to change directory into the repository?

The full quickstart should probably be:

```shell
git clone https://github.com/edwardqnguyen/awbw2-electricboogaloo

cd awbw2-elecrtricboogaloo

yarn install
yarn build
yarn dev
```

Let me know if this works and I'll submit a PR to update the quickstart.

Thanks,
Ana

**Comment by edwardqnguyen** [comment]
I'll update the readme
